---

- name: configure first example
  hosts: localhost # This is where this task will run - not where the affected machines are
  tasks:

    - name: create key pair on aws using key_material obtained using 'file' lookup plugin
      amazon.aws.ec2_key:
        name: ucgajhe_aws_dev_keypair
        key_material: "{{ lookup('file', '/Users/jamespjh/.ssh/aws_rsa.pub') }}"

    - name: get the data about vpcs
      amazon.aws.ec2_vpc_net_info:
        filters:
          "tag:Name": ARC-playpen
      register: vpcs 

    - name: get the data about subnets
      amazon.aws.ec2_vpc_subnet_info:
        filters:
          vpc-id: "{{vpcs.vpcs[0].id}}"
          "tag:Name": "playpen-public-eu-west-2a"
      register: subnets

    - name: create a security group
      amazon.aws.ec2_security_group:
        name: course_security_group
        description: course security group
        vpc_id: "{{vpcs.vpcs[0].id}}"
        region: eu-west-2
        rules:
          - proto: tcp
            ports: 22
            cidr_ip: 38.242.173.89/32
            rule_desc: allow all IP on SSH

    - name: create the first course instance
      amazon.aws.ec2_instance:
        name: ucgajhe-dev-instance
        key_name: ucgajhe_aws_dev_keypair
        vpc_subnet_id: "{{subnets.subnets[0].subnet_id}}"
        instance_type: t2.micro
        security_group: course_security_group
        network:
          assign_public_ip: true
        image_id: ami-0f9bfd7d2738e70d5
        tags:
          Owner: ucgajhe
