---

- name: configure first example
  hosts: localhost # This is where this task will run - not where the affected machines are
  tasks:

    - name: create key pair on aws using key_material obtained using 'file' lookup plugin
      #https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_key_module.html
      amazon.aws.ec2_key:
        region: eu-west-2
        name: ucgajhe_aws_dev_keypair
        key_material: "{{ lookup('file', '/Users/jamespjh/.ssh/aws_rsa.pub') }}"

    - name: get the data about vpcs
    # https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_vpc_net_info_module.html
      amazon.aws.ec2_vpc_net_info:
        filters:
          "tag:Name": ARC-playpen
      register: vpcs 

    - name: get the data about subnets
      amazon.aws.ec2_vpc_subnet_info:
        filters:
          vpc-id: "{{vpcs.vpcs[0].id}}"
          "tag:Name": "playpen-public-eu-west-2a"
      register: subnets

    - name: create a security group
    # https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_security_group_module.html
      amazon.aws.ec2_security_group:
        name: course_security_group
        description: course security group
        vpc_id: "{{vpcs.vpcs[0].id}}"
        region: eu-west-2
        rules:
          - proto: tcp
            ports: 22
            cidr_ip: 38.242.0.0/16
            rule_desc: allow my IP on SSH

    - name: create the instances
      # https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_instance_module.html
      amazon.aws.ec2_instance:
        name: "ucgajhe-{{item}}-instance"
        key_name: ucgajhe_aws_dev_keypair
        vpc_subnet_id: "{{subnets.subnets[0].subnet_id}}"
        instance_type: "{{item}}"
        security_group: course_security_group
        network:
          assign_public_ip: true
        image_id: ami-0f9bfd7d2738e70d5
        tags:
          Owner: ucgajhe
      loop:
        - t2.micro
        - c4.2xlarge

    - name: Gather information instances
    # https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_instance_info_module.html
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Owner": ucgajhe
          instance-state-name: running
      register: instance_info

    - name: create storage volumes for the data for each instance and attach to the instances
    # https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_vol_module.html
      amazon.aws.ec2_vol:
        instance: "{{item.instance_id}}"
        delete_on_termination: true
        tags:
          Owner: ucgajhe
        volume_size: 128 #GiB
        volume_type: gp3
        name: datastorage-{{item.instance_id}} # prevent recreation if it exists
      loop: "{{instance_info.instances}}"




- name: on the device, get the data volume mounted and ready to use
  hosts: aws_ec2
  tasks:
    - name: create a mount point for the data volume
      ansible.builtin.file:
        path: data/
        state: directory
        mode: '0755' 
    - name: format the volume as ext4
      community.general.filesystem:
        dev: /dev/xvdf
        fstype: ext4
      become: true
    - name: mount the filesystem
      ansible.posix.mount:
        name: data
        src: /dev/xvdf
        fstype: ext4
        state: mounted 
      become: true
    - name: change the owner back to ec2-user after mounting
      become: true
      ansible.builtin.file:
        path: data/
        state: directory
        mode: 0755
        owner: ec2-user

