- name: configure our DB example
  hosts: localhost # This is where this task will run - not where the affected machines are
  tasks:

    - name: Connect to the primary we just made, and create a DB
      community.postgresql.postgresql_db:
        name: molecules
        login_host: "{{database.endpoint.address}}"
        login_password: TeachingDataEngineeringInsecurely
        login_user: jamespjh

    - name: Connect to the primary we just made, and create a simple table
      # E.g.  engine =  psycopg2.connect(database='postgres',user='jamespjh',
      # password='TeachingDataEngineeringInsecurely',host='exemplar-db.cvvluwyhowbt.eu-west-2.rds.amazonaws.com',port=5432)
      # https://galaxy.ansible.com/ui/repo/published/community/postgresql/content/module/postgresql_table/
      community.postgresql.postgresql_table:
        login_host: "{{database.endpoint.address}}"
        login_password: TeachingDataEngineeringInsecurely
        login_user: jamespjh
        name: molecule_elements
        db: molecules
        columns:
        - molecule text primary key
        - num int
        - element text

    - name: Connect to the primary we just made, and run a SQL insert query
      community.postgresql.postgresql_query:
        login_host: "{{database.endpoint.address}}"
        login_password: TeachingDataEngineeringInsecurely
        login_user: jamespjh
        db: molecules
        query: INSERT INTO molecule_elements (molecule, num, element) VALUES ('co2', 1, 'c')

    - name: Connect to a replicate we just made, and run a SQL query
      community.postgresql.postgresql_query:
        login_host: "{{replicates.results[0].endpoint.address}}"
        login_password: TeachingDataEngineeringInsecurely
        login_user: jamespjh
        db: molecules
        query: SELECT * FROM molecule_elements
      register: result

    - name: Print the example
      ansible.builtin.debug:
        var: result           
