# Ansible inventory for development
# https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html
plugin: amazon.aws.aws_ec2
boto_profile: dataeng-course
regions:
    - eu-west-2
compose:
  ansible_host: public_dns_name
  ansible_user: "'ec2-user'"
  ansible_ssh_private_key_file: "'/Users/jamespjh/.ssh/aws_rsa'"
  ansible_ssh_common_args: "'-o StrictHostKeyChecking=no'"
filters:
  tag:Owner:
    - ucgajhe
keyed_groups:
  # Add hosts to tag_Name_Value groups for each Name/Value tag pair
  - prefix: tag
    key: tags

