- name: on the device, get the data volume mounted and ready to use
  hosts: tag_Type_exemplar
  tasks:
    - name: create a mount point for the data volume
      ansible.builtin.file:
        path: data/
        state: directory
        mode: '0755' 
    - name: format the volume as ext4
      community.general.filesystem:
        dev: /dev/xvdf
        fstype: ext4
      become: true
    - name: mount the filesystem
      ansible.posix.mount:
        name: data
        src: /dev/xvdf
        fstype: ext4
        state: mounted 
      become: true
    - name: change the owner back to ec2-user after mounting
      become: true
      ansible.builtin.file:
        path: data/
        state: directory
        mode: 0755
        owner: ec2-user