- name: copy the subset of data for this node
  ansible.builtin.shell: |
    cd data/local_corpus
    ../../manifest_local.txt | xargs -Itarget cp -u target .
  # The -u flag to cp makes this idempotent