
- name: Set up the private key so the clients can ssh to the host
  ansible.builtin.copy:
    dest: /home/ec2-user/.ssh/id_rsa
    src: "/Users/jamespjh/.ssh/cluster-key"
    mode: '600'

- name: Install yum packages
  ansible.builtin.yum:
    name: "{{ packages }}"
  become: true
  vars:
    packages:
    - python
    - python-pip
    - unzip
    - git
    - wget
    - make
    - rpm-build

- name: install this package from from git
  ansible.builtin.pip:
    name: git+https://github.com/jamespjh/EngineeringForDataAnalysisExamples.git
    state: forcereinstall

- name: Create temp folder for builds
  ansible.builtin.file:
    path: build
    state: directory
- name: Git checkout the EFS utilities
  ansible.builtin.git:
    repo: 'https://github.com/aws/efs-utils'
    dest: build/efs-utils
- name: Build EFS
  community.general.make:
    chdir: build/efs-utils
    target: rpm
- name: Install yum EFS
  become: true
  ansible.builtin.yum:
    name: /home/ec2-user/build/efs-utils/build/amazon-efs-utils-1.35.0-1.el9.noarch.rpm
    state: present
    disable_gpg_check: true
- name: Make a mountpoint for the EFS
  ansible.builtin.file:
      path: efs/
      state: directory
      mode: '0755' 
- name: mount the EFS
  become: true
  ansible.posix.mount:
    path: efs/
    src: "{{hostvars['localhost'].efs.efs.mount_targets[0].file_system_id}}"
    fstype: efs
    state: mounted 
  become: true
- name: change the owner back to ec2-user after mounting
  become: true
  ansible.builtin.file:
    path: efs/
    state: directory
    mode: u+rwx,a+x
    owner: ec2-user

- name: generate a partial manifest on each client
  ansible.builtin.shell: "ls -d efs/1850_1859/ | awk '!((NR+{{rank}}) %{{size}})' > manifest_local.txt"
- name: make a local corpus folder on the client to keep the local files to analyse in
  ansible.builtin.file:
    path: data/local_corpus
    state: directory
    mode: 0755 
- name: Create temp folder for incomplete downloads on larger volume
  ansible.builtin.file:
    path: data/tmp
    state: directory
    mode: 0755