
- name: Set up the private key so the clients can ssh to the host
  ansible.builtin.copy:
    dest: /home/ec2-user/.ssh/id_rsa
    src: "/Users/jamespjh/.ssh/cluster-key"
    mode: '600'

- name: Install yum packages
  ansible.builtin.yum:
    name: "{{ packages }}"
  become: true
  vars:
    packages:
    - python
    - python-pip
    - unzip
    - git
    - wget
- name: install this package from from git
  ansible.builtin.pip:
    name: git+https://github.com/jamespjh/EngineeringForDataAnalysisExamples.git
    state: forcereinstall
- name: install awscli
  ansible.builtin.pip:
    name: awscli
- name: generate a variable of keys in s3 for objects to process on all nodes
  amazon.aws.s3_object:
    bucket: data-bucket-books-example
    mode: list
  register: objects
- name: write a file containing the list of objects to process
  ansible.builtin.template:
    src: manifest.j2
    dest: manifest.txt
- name: generate a partial manifest on each client
  ansible.builtin.shell: "awk '!((NR+{{rank}}) %{{size}})' manifest.txt > manifest_local.txt"
- name: make a local corpus folder on the client to keep the local files to analyse in
  ansible.builtin.file:
    path: data/local_corpus
    state: directory
    mode: 0755 
- name: Create temp folder for incomplete downloads on larger volume
  ansible.builtin.file:
    path: data/tmp
    state: directory
    mode: 0755