
- name: create instances
  amazon.aws.ec2_instance:
    name: "cluster-client-{{item}}"
    key_name: ucgajhe_aws_dev_keypair
    vpc_subnet_id: "{{subnets.subnets[0].subnet_id}}"
    instance_type: t3.small
    security_group: cluster_security_group
    #iam_instance_profile: arn:aws:iam::206627141809:instance-profile/EC2ReadTagsRole
    # Above is to allow the instances to query their own metadata via boto
    network:
      assign_public_ip: true
    image_id: ami-0f9bfd7d2738e70d5
    tags:
      Owner: ucgajhe
      Role: client
      Rank: "{{item}}"
      Size: "{{cluster_size}}"
    state: running
  loop: "{{range(cluster_size)}}"
- name: Refresh inventory to ensure new instances exist in inventory
  ansible.builtin.meta: refresh_inventory
