

- name: prepare the headnode
  hosts: tag_Type_Headnode
  vars:
    targets:
      - 1850-1859
  tasks:
  - name: prepare the headnode
    include_tasks: 
      file: hc_headnode.yml

- name: prepare the workers
  hosts: tag_Type_Worker
  vars: 
    rank: "{{ansible_local['custom']['cluster']['rank']}}"
    size:  "{{ansible_local['custom']['cluster']['size']}}"
    headnode_private_ip: "{{ansible_local['custom']['cluster']['headnode_private_ip']}}"
  tasks:
    - name: set up the worker nodes
      include_tasks: hc_workers.yml
    - name: fetch the data on the worker nodes
      include_tasks: hc_data.yml 
    - name: run the analysis
      include_tasks: hc_analyse.yml

- name: Combine the results on the headnode and print
  hosts: tag_Type_Headnode
  tasks:
    - name: Combine the results and print
      include_tasks: hc_combine.yml