- name: prepare the instances
  vars:
    cluster_size: 16
  hosts: localhost
  tasks:
  - name: create the headnode instances
    include_tasks: hc_headnode_instances.yml
  - name: create the worker instances
    include_tasks: hc_worker_instances.yml


- name: get info about made instances
  hosts: localhost
  tasks:
    - name: get info about instances
      include_tasks: hc_instance_info.yml
    
- name: get rank and size info on workers
  hosts: tag_Role_client
  tasks:
    - name: get info about rank and size
      include_tasks: hc_worker_info.yml

# - name: prepare the headnode
#   hosts: tag_Role_host
#   vars:
#     targets:
#       - 1850-1859
#   tasks:
#   - name: prepare the headnode
#     include_tasks: 
#       file: hc_headnode.yml

- name: prepare the workers
  hosts: tag_Role_client
  tasks:
    - name: set up the worker nodes
      include_tasks: hc_workers.yml
    - name: fetch the data on the worker nodes
      include_tasks: hc_data.yml 

- name: run the analysis
  hosts: tag_Role_client
  tasks:
    - name: run the analysis
      include_tasks: hc_analyse.yml

- name: Combine the results on the headnode and print
  hosts: tag_Role_host
  tasks:
    - name: Combine the results and print
      include_tasks: hc_combine.yml