---
- name: Prepare the code to run on the remote
  hosts: aws_ec2
  tasks:
    - name: Install yum packages
      ansible.builtin.yum:
        name: "{{ packages }}"
      become: true
      vars:
        packages:
        - python
        - python-pip
    - name: install this package from from git
      ansible.builtin.pip:
        name: git+https://github.com/jamespjh/EngineeringForDataAnalysisExamples.git
