- name: configure our DB example
  hosts: localhost # This is where this task will run - not where the affected machines are
  tasks:
    - name: create key pair on aws using key_material obtained using 'file' lookup plugin
      #https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_key_module.html
      amazon.aws.ec2_key:
        region: eu-west-2
        name: ucgajhe_aws_db_keypair
        key_material: "{{ lookup('file', '/Users/jamespjh/.ssh/id_rsa.pub') }}"

    - name: get the data about vpcs
    # https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_vpc_net_info_module.html
      amazon.aws.ec2_vpc_net_info:
        filters:
          "tag:Name": ARC-playpen
      register: vpcs 

    - name: get the data about subnets
      amazon.aws.ec2_vpc_subnet_info:
        filters:
          vpc-id: "{{vpcs.vpcs[0].id}}"
          "tag:Name": "playpen-public-eu-west-2a"
      register: subnets


    - name: create a security group
      # https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_security_group_module.html
      amazon.aws.ec2_security_group:
        name: course_db_security_group
        description: course security group
        vpc_id: "{{vpcs.vpcs[0].id}}"
        region: eu-west-2
        rules:
          - proto: tcp
            ports: 5432
            cidr_ip: 38.242.0.0/16
            rule_desc: allow my IP on Postgres
          - proto: tcp
            ports: 22
            cidr_ip: 38.242.0.0/16
            rule_desc: allow my IP on SSH
      register: security_group      

    - name: create the instance
      # https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_instance_module.html
      amazon.aws.ec2_instance:
        name: "ucgajhe-DB-instance"
        key_name: ucgajhe_aws_db_keypair
        vpc_subnet_id: "{{subnets.subnets[0].subnet_id}}"
        instance_type: "t2.large"
        security_group: course_db_security_group
        network:
          assign_public_ip: true
        image_id: ami-0f9bfd7d2738e70d5
        tags:
          Owner: ucgajhe
          Type: DB

    - name: Gather information instances
    # https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_instance_info_module.html
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Owner": ucgajhe
          "tag:Type": DB
          instance-state-name: running
      register: instance_info