- name: Set up an EMR cluster, and use it to solve the British Library example.
  hosts: localhost

  tasks:
    - name: get the data about vpcs
    # https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_vpc_net_info_module.html
      amazon.aws.ec2_vpc_net_info:
        filters:
          "tag:Name": ARC-playpen
      register: vpcs 

    - name: get the data about subnets
      amazon.aws.ec2_vpc_subnet_info:
        filters:
          vpc-id: "{{vpcs.vpcs[0].id}}"
          "tag:Name": "playpen-public-eu-west-2a"
      register: subnets

    - name: create an additional security group for the cluster
    # https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_security_group_module.html
      amazon.aws.ec2_security_group:
        name: emr_security_group
        description: course security group
        vpc_id: "{{vpcs.vpcs[0].id}}"
        region: eu-west-2
        rules:
          - proto: tcp
            ports: 22
            cidr_ip: 38.242.0.0/16
            rule_desc: allow my IP on SSH
          - proto: tcp
            ports: 80
            cidr_ip: 38.242.0.0/16
            rule_desc: allow my IP on WWW

    # There's no ansible task for this, we have to use the EC2 CLI.
    # The CLI command expects a number of JSON files with configuration information
    # Which we create as YAML data structures and then turn into JSON,
    # then write to the disk and pass as file-paths to the cli
    # Rather than check in the created json files, we use a template to pass in security group information for one of them
    
    - name: Create the file containing attribute information
      ansible.builtin.template:
        src: emr_attributes.j2
        dest: emr_attributes.json

    - name: Create an EMR cluster
      vars:
        command: >-
          aws emr create-cluster 
          --release-label emr-6.14.0 
          --instance-groups file://emr_groups.json
          --name course-cluster-emr-ucgajhe 
          --ec2-attributes file://emr_attributes.json
          --tags Owner=ucgajhe,Course=comp0235,Type=EMR 
          --applications Name=Spark
      ansible.builtin.debug:
        var: command
