- name: get facts about this instance, and add them to the hostvars
  amazon.aws.ec2_metadata_facts:
# - name: get more facts about this instance and register them
# # This is much more of a faff than it should be
#   amazon.aws.ec2_instance_info:
#     region: eu-west-2
#     instance_ids: "{{ansible_ec2_instance_id}}"
#   register: facts_about_this_instance
- name: Tell the instance about its rank and size in the cluster
  ansible.builtin.set_fact: 
    rank: "{{( hostvars['localhost'].client_info.instances | selectattr('instance_id','equalto',ansible_ec2_instance_id) )[0].tags.Rank}}"
    size: "{{( hostvars['localhost'].client_info.instances | selectattr('instance_id','equalto',ansible_ec2_instance_id) )[0].tags.Size}}"

# Put a file on the instance telling it about its rank and size 