---
- name: Stop the instance
  hosts: localhost
  tasks:
    - name: Stop the instance
      amazon.aws.ec2_instance:
        state: terminated
        wait: True
        filters:
          instance-state-name: running
          tag:Owner: ucgajhe
          tag:Role: client